# -*- mode: ruby -*-
#vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "host1"
  #config.vm.define "host2"
  #config.vm.define "host3"
  # config.vm.define "host2"
  #config.vm.network :forwarded_port, guest: 80, host: 4567
  config.vm.box = "ubuntu/focal64"
  #
  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "ansible/install_rundeck.yml"
  #end
  #config.vm.network "forwarded_port", guest: 8080, host: 8081
  #config.vm.network "forwarded_port", guest: 7443, host: 7443
  # config.vm.box_check_update = false
  #config.vm.network "forwarded_port", guest: 4440, host: 4440
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
   vb.memory = "4096"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     #apt-get install apache2 -y
  #   apt-get upgrade -y
   SHELL
end
